---
title: "Introdução"
author: "Rawicz"
date: "26 de junho de 2017"
output: pdf_document
---


O objetivo do trabalho é analisar as formas pelas quais são expressados sentimentos negativos nas redes sociais. Isso se dá devido à grande importância da análise desses sentimentos, já que segundo a Organização Mundial de Saúde, estima-se que 300 milhões de pessoas sofram de depressão ao redor do mundo, o que representa um incremento de 18% entre 2005 e 2015.[1] Além disso, o WHO mostra que no pior dos casos, a depressão leva ao suicídio, sendo que é estimado que 800 000 pessoas morram de suicídio todos os anos, sendo a segunda maior causa de morte entre jovens de 15 a 29 anos. 

Além disso, a depressão pode ter vários tipos de impactos na sociedade, Marcotte e Wilcox-Gök(2001),[2] por exemplo, estimam os custos de emprego e renda da depressão, mostrando que existem diversos tipos de custos além de tratamentos e remédios, já que pessoas com depressão estão mais propensas a perder seu emprego e têm mais dificuldade de inserção no mercado de trabalho.

Mas na incapacidade de identificar as pessoas com algum caso clínico de depressão, foram utilizados dados de palavras relacionadas à sentimentos negativos na rede social "twitter", que por ser considerado um *"microblog"* no qual as pessoas postam constantemente e, segundo o site "Statista", tinha 328 milhões de usuários até o fim de março de 2017, sendo que o mesmo site mostrou que é a rede que teve o maior engajamento nos primeiros quatro meses do mesmo ano.

Portanto, foi a Rede Social que melhor se ajustava às necessidades de busca textual sobre os sentimentos negativos e como eles eram expressados socialmente pelas pessoas. Na análise foi feita a busca no idioma inglês devido à maior disponibilidade de dados.

Além dessa introdução, o trabalho é dividido em metodologia, nos resultados e em uma conclusão.









[1]WHO, “Depression, let's talk” in The World Health Report 2001, 2001, http://www.who.int/mental_health/management/depression/en/.


[2]D. E. Marcotte and V. Wilcox-Gök, “Estimating the employment and earnings costs of mental illness: recent developments in the United States,” Social Science and Medicine, vol. 53, no. 1, pp. 21–27, 2001.

[3]https://www.statista.com/statistics/282087/number-of-monthly-active-twitter-users/, acesso em 22/06/2017





















